function [Y,Xf,Af] = multilayerPerceptronNeuralNetwork10(X,~,~)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Auto-generated by MATLAB, 16-Jun-2021 20:45:27.
%
% [Y] = myNeuralNetworkFunction(X,~,~) takes these arguments:
%
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = Qx1 matrix, input #1 at timestep ts.
%
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = Qx1 matrix, output #1 at timestep ts.
%
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = 0.04;
x1_step1.gain = 0.0809716599190283;
x1_step1.ymin = -1;

% Layer 1
b1 = [13.419549044146018346;11.225290522861341103;7.8647292753864590509;-2.2875860119122202185;-0.57834339212643059991;-2.6457086517956951432;-7.5090141377888164342;-1.637052901328630794;13.996734696449699697;-19.931698094669339838];
IW1_1 = [-13.438114052515546248;-14.456929725338898862;-14.333154978689586656;13.80109609571496776;-11.41856557686136675;-9.3892365191454345563;-24.937544160671230031;-3.651320936535892514;17.573012702192244205;-21.385924490472309145];

% Layer 2
b2 = -0.032031987631885132373;
LW2_1 = [0.0025431795025804811508 -0.0007814274854440908611 0.0021703201228774919238 -0.011259636100423676269 0.051897304659249361702 -0.51858711023179415722 0.087548429324564067122 -0.68741406414825345639 -0.052480309207423352091 0.015240462180967090031];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = 0.000526268702274007;
y1_step1.xoffset = -25.78;

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
    X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},1); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS
    
    % Input 1
    X{1,ts} = X{1,ts}';
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1);
    Y{1,ts} = Y{1,ts}';
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX
    Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
y = bsxfun(@minus,x,settings.xoffset);
y = bsxfun(@times,y,settings.gain);
y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
x = bsxfun(@minus,y,settings.ymin);
x = bsxfun(@rdivide,x,settings.gain);
x = bsxfun(@plus,x,settings.xoffset);
end
